// Generated 36 States & UTs to Districts mapping
export const STATE_DISTRICTS_MAP: Record<string, string[]> = {
  "Andaman And Nicobar Islands": [
    "NICOBARS",
    "NORTH AND MIDDLE ANDAMAN",
    "SOUTH ANDAMANS"
  ],
  "ANDAMAN AND NICOBAR ISLANDS": [
    "NICOBARS",
    "NORTH AND MIDDLE ANDAMAN",
    "SOUTH ANDAMANS"
  ],
  "Andhra Pradesh": [
    "ALLURI SITHARAMA RAJU",
    "ANAKAPALLI",
    "ANANTHAPURAMU",
    "ANNAMAYYA",
    "BAPATLA",
    "CHITTOOR",
    "DR. B.R. AMBEDKAR KONASEEMA",
    "EAST GODAVARI",
    "EAST KHASI HILLS",
    "ELURU",
    "GORAKHPUR",
    "GUNTUR",
    "KAKINADA",
    "KRISHNA",
    "KURNOOL",
    "MAHABUBNAGAR",
    "NANDYAL",
    "NARAYANPET",
    "NIZAMABAD",
    "NTR",
    "PALNADU",
    "PARVATHIPURAM MANYAM",
    "PRAKASAM",
    "SIDDIPET",
    "SRI POTTI SRIRAMULU NELLORE",
    "SRI SATHYA SAI",
    "SRIKAKULAM",
    "TIRUPATI",
    "VISAKHAPATNAM",
    "VIZIANAGARAM",
    "WEST GODAVARI",
    "Y.S.R. KADAPA"
  ],
  "ANDHRA PRADESH": [
    "ALLURI SITHARAMA RAJU",
    "ANAKAPALLI",
    "ANANTHAPURAMU",
    "ANNAMAYYA",
    "BAPATLA",
    "CHITTOOR",
    "DR. B.R. AMBEDKAR KONASEEMA",
    "EAST GODAVARI",
    "EAST KHASI HILLS",
    "ELURU",
    "GORAKHPUR",
    "GUNTUR",
    "KAKINADA",
    "KRISHNA",
    "KURNOOL",
    "MAHABUBNAGAR",
    "NANDYAL",
    "NARAYANPET",
    "NIZAMABAD",
    "NTR",
    "PALNADU",
    "PARVATHIPURAM MANYAM",
    "PRAKASAM",
    "SIDDIPET",
    "SRI POTTI SRIRAMULU NELLORE",
    "SRI SATHYA SAI",
    "SRIKAKULAM",
    "TIRUPATI",
    "VISAKHAPATNAM",
    "VIZIANAGARAM",
    "WEST GODAVARI",
    "Y.S.R. KADAPA"
  ],
  "Arunachal Pradesh": [
    "ANJAW",
    "CHANGLANG",
    "EAST KAMENG",
    "EAST SIANG",
    "KAMLE",
    "KURUNG KUMEY",
    "LEPARADA",
    "LOHIT",
    "LONGDING",
    "LOWER DIBANG VALLEY",
    "LOWER SIANG",
    "LOWER SUBANSIRI",
    "NAMSAI",
    "PAPUM PARE",
    "SIANG",
    "TAWANG",
    "TIRAP",
    "UPPER SIANG",
    "UPPER SUBANSIRI",
    "WEST KAMENG",
    "WEST SIANG"
  ],
  "ARUNACHAL PRADESH": [
    "ANJAW",
    "CHANGLANG",
    "EAST KAMENG",
    "EAST SIANG",
    "KAMLE",
    "KURUNG KUMEY",
    "LEPARADA",
    "LOHIT",
    "LONGDING",
    "LOWER DIBANG VALLEY",
    "LOWER SIANG",
    "LOWER SUBANSIRI",
    "NAMSAI",
    "PAPUM PARE",
    "SIANG",
    "TAWANG",
    "TIRAP",
    "UPPER SIANG",
    "UPPER SUBANSIRI",
    "WEST KAMENG",
    "WEST SIANG"
  ],
  "Assam": [
    "BARPETA",
    "BISWANATH",
    "BONGAIGAON",
    "CHARAIDEO",
    "CHIRANG",
    "DARRANG",
    "DHEMAJI",
    "DHUBRI",
    "GOALPARA",
    "JORHAT",
    "KAMRUP",
    "KAMRUP METRO",
    "KARBI ANGLONG",
    "KOKRAJHAR",
    "LAKHIMPUR",
    "MAJULI",
    "MARIGAON",
    "NAGAON",
    "NALBARI",
    "SIVASAGAR",
    "SONITPUR",
    "SOUTH SALMARA MANCACHAR",
    "SRIBHUMI",
    "TINSUKIA",
    "UDALGURI",
    "WEST KARBI ANGLONG"
  ],
  "ASSAM": [
    "BARPETA",
    "BISWANATH",
    "BONGAIGAON",
    "CHARAIDEO",
    "CHIRANG",
    "DARRANG",
    "DHEMAJI",
    "DHUBRI",
    "GOALPARA",
    "JORHAT",
    "KAMRUP",
    "KAMRUP METRO",
    "KARBI ANGLONG",
    "KOKRAJHAR",
    "LAKHIMPUR",
    "MAJULI",
    "MARIGAON",
    "NAGAON",
    "NALBARI",
    "SIVASAGAR",
    "SONITPUR",
    "SOUTH SALMARA MANCACHAR",
    "SRIBHUMI",
    "TINSUKIA",
    "UDALGURI",
    "WEST KARBI ANGLONG"
  ],
  "Bihar": [
    "ARARIA",
    "ARWAL",
    "AURANGABAD",
    "BANKA",
    "BEGUSARAI",
    "BHAGALPUR",
    "BHOJPUR",
    "BUXAR",
    "DARBHANGA",
    "GAYA",
    "GOPALGANJ",
    "JAMUI",
    "JEHANABAD",
    "KAIMUR",
    "KATIHAR",
    "KHAGARIA",
    "KISHANGANJ",
    "MADHEPURA",
    "MADHUBANI",
    "MUNGER",
    "MUZAFFARPUR",
    "NALANDA",
    "NAWADA",
    "PASHCHIM CHAMPARAN",
    "PATNA",
    "PURBI CHAMPARAN",
    "PURNIA",
    "ROHTAS",
    "SAHARSA",
    "SAMASTIPUR",
    "SARAN",
    "SHEIKHPURA",
    "SHEOHAR",
    "SITAMARHI",
    "SIWAN",
    "SUPAUL",
    "VAISHALI"
  ],
  "BIHAR": [
    "ARARIA",
    "ARWAL",
    "AURANGABAD",
    "BANKA",
    "BEGUSARAI",
    "BHAGALPUR",
    "BHOJPUR",
    "BUXAR",
    "DARBHANGA",
    "GAYA",
    "GOPALGANJ",
    "JAMUI",
    "JEHANABAD",
    "KAIMUR",
    "KATIHAR",
    "KHAGARIA",
    "KISHANGANJ",
    "MADHEPURA",
    "MADHUBANI",
    "MUNGER",
    "MUZAFFARPUR",
    "NALANDA",
    "NAWADA",
    "PASHCHIM CHAMPARAN",
    "PATNA",
    "PURBI CHAMPARAN",
    "PURNIA",
    "ROHTAS",
    "SAHARSA",
    "SAMASTIPUR",
    "SARAN",
    "SHEIKHPURA",
    "SHEOHAR",
    "SITAMARHI",
    "SIWAN",
    "SUPAUL",
    "VAISHALI"
  ],
  "Chandigarh": [
    "CHANDIGARH",
    "LEH LADAKH",
    "MOGA",
    "RUPNAGAR"
  ],
  "CHANDIGARH": [
    "CHANDIGARH",
    "LEH LADAKH",
    "MOGA",
    "RUPNAGAR"
  ],
  "Chhattisgarh": [
    "BALOD",
    "BALODABAZAR-BHATAPARA",
    "BALRAMPUR-RAMANUJGANJ",
    "BASTAR",
    "BEMETARA",
    "BIJAPUR",
    "BILASPUR",
    "DHAMTARI",
    "DURG",
    "GARIYABAND",
    "GAURELA-PENDRA-MARWAHI",
    "JANJGIR-CHAMPA",
    "JASHPUR",
    "KABEERDHAM",
    "KHAIRAGARH-CHHUIKHADAN-GANDAI",
    "KONDAGAON",
    "KORBA",
    "KOREA",
    "MAHASAMUND",
    "MANENDRAGARH-CHIRMIRI-BHARATPUR",
    "MUNGELI",
    "MUZAFFARPUR",
    "NARAYANPUR",
    "PAPUM PARE",
    "RAIGARH",
    "RAIPUR",
    "RAJNANDGAON",
    "SAKTI",
    "SARANGARH-BILAIGARH",
    "SUKMA",
    "SURAJPUR",
    "SURGUJA",
    "UTTAR BASTAR KANKER"
  ],
  "CHHATTISGARH": [
    "BALOD",
    "BALODABAZAR-BHATAPARA",
    "BALRAMPUR-RAMANUJGANJ",
    "BASTAR",
    "BEMETARA",
    "BIJAPUR",
    "BILASPUR",
    "DHAMTARI",
    "DURG",
    "GARIYABAND",
    "GAURELA-PENDRA-MARWAHI",
    "JANJGIR-CHAMPA",
    "JASHPUR",
    "KABEERDHAM",
    "KHAIRAGARH-CHHUIKHADAN-GANDAI",
    "KONDAGAON",
    "KORBA",
    "KOREA",
    "MAHASAMUND",
    "MANENDRAGARH-CHIRMIRI-BHARATPUR",
    "MUNGELI",
    "MUZAFFARPUR",
    "NARAYANPUR",
    "PAPUM PARE",
    "RAIGARH",
    "RAIPUR",
    "RAJNANDGAON",
    "SAKTI",
    "SARANGARH-BILAIGARH",
    "SUKMA",
    "SURAJPUR",
    "SURGUJA",
    "UTTAR BASTAR KANKER"
  ],
  "Delhi": [
    "CENTRAL",
    "EAST",
    "NEW DELHI",
    "NORTH",
    "NORTH WEST",
    "SOUTH",
    "SOUTH EAST",
    "SOUTH WEST",
    "WEST"
  ],
  "DELHI": [
    "CENTRAL",
    "EAST",
    "NEW DELHI",
    "NORTH",
    "NORTH WEST",
    "SOUTH",
    "SOUTH EAST",
    "SOUTH WEST",
    "WEST"
  ],
  "Goa": [
    "NORTH GOA",
    "SHAHJAHANPUR",
    "SOUTH GOA"
  ],
  "GOA": [
    "NORTH GOA",
    "SHAHJAHANPUR",
    "SOUTH GOA"
  ],
  "Gujarat": [
    "AHMEDABAD",
    "AMRELI",
    "ANAND",
    "ARVALLI",
    "BANAS KANTHA",
    "BHARUCH",
    "BHAVNAGAR",
    "BOTAD",
    "CHHOTAUDEPUR",
    "DAHOD",
    "DANGS",
    "DEVBHUMI DWARKA",
    "GANDHINAGAR",
    "GIR SOMNATH",
    "JAMNAGAR",
    "JUNAGADH",
    "KACHCHH",
    "KHEDA",
    "MAHESANA",
    "MAHISAGAR",
    "MORBI",
    "NARMADA",
    "NAVSARI",
    "PANCH MAHALS",
    "PATAN",
    "PORBANDAR",
    "RAJKOT",
    "SABAR KANTHA",
    "SURAT",
    "SURENDRANAGAR",
    "TAPI",
    "VADODARA",
    "VALSAD"
  ],
  "GUJARAT": [
    "AHMEDABAD",
    "AMRELI",
    "ANAND",
    "ARVALLI",
    "BANAS KANTHA",
    "BHARUCH",
    "BHAVNAGAR",
    "BOTAD",
    "CHHOTAUDEPUR",
    "DAHOD",
    "DANGS",
    "DEVBHUMI DWARKA",
    "GANDHINAGAR",
    "GIR SOMNATH",
    "JAMNAGAR",
    "JUNAGADH",
    "KACHCHH",
    "KHEDA",
    "MAHESANA",
    "MAHISAGAR",
    "MORBI",
    "NARMADA",
    "NAVSARI",
    "PANCH MAHALS",
    "PATAN",
    "PORBANDAR",
    "RAJKOT",
    "SABAR KANTHA",
    "SURAT",
    "SURENDRANAGAR",
    "TAPI",
    "VADODARA",
    "VALSAD"
  ],
  "Haryana": [
    "AMBALA",
    "BHIWANI",
    "CHARKHI DADRI",
    "FARIDABAD",
    "FATEHABAD",
    "GURUGRAM",
    "HISAR",
    "JHAJJAR",
    "JIND",
    "KAITHAL",
    "KURUKSHETRA",
    "MAHENDRAGARH",
    "NUH",
    "PALWAL",
    "PANCHKULA",
    "PANIPAT",
    "REWARI",
    "ROHTAK",
    "SIRSA",
    "SONIPAT",
    "VARANASI"
  ],
  "HARYANA": [
    "AMBALA",
    "BHIWANI",
    "CHARKHI DADRI",
    "FARIDABAD",
    "FATEHABAD",
    "GURUGRAM",
    "HISAR",
    "JHAJJAR",
    "JIND",
    "KAITHAL",
    "KURUKSHETRA",
    "MAHENDRAGARH",
    "NUH",
    "PALWAL",
    "PANCHKULA",
    "PANIPAT",
    "REWARI",
    "ROHTAK",
    "SIRSA",
    "SONIPAT",
    "VARANASI"
  ],
  "Himachal Pradesh": [
    "BILASPUR",
    "CHAMBA",
    "HAMIRPUR",
    "KANGRA",
    "KULLU",
    "MANDI",
    "MOHLA-MANPUR-AMBAGARH CHOUKI",
    "SHIMLA",
    "SIRMAUR",
    "SOLAN",
    "UNA"
  ],
  "HIMACHAL PRADESH": [
    "BILASPUR",
    "CHAMBA",
    "HAMIRPUR",
    "KANGRA",
    "KULLU",
    "MANDI",
    "MOHLA-MANPUR-AMBAGARH CHOUKI",
    "SHIMLA",
    "SIRMAUR",
    "SOLAN",
    "UNA"
  ],
  "Jammu And Kashmir": [
    "ANANTNAG",
    "BANDIPORA",
    "BARAMULLA",
    "BUDAUN",
    "BUDGAM",
    "CHANDAULI",
    "DODA",
    "GANDERBAL",
    "JAMMU",
    "KATHUA",
    "KUPWARA",
    "PILIBHIT",
    "POONCH",
    "PULWAMA",
    "RAJOURI",
    "RAMBAN",
    "REASI",
    "SAMBA",
    "SHAHJAHANPUR",
    "SHOPIAN",
    "SRINAGAR",
    "UDHAMPUR"
  ],
  "JAMMU AND KASHMIR": [
    "ANANTNAG",
    "BANDIPORA",
    "BARAMULLA",
    "BUDAUN",
    "BUDGAM",
    "CHANDAULI",
    "DODA",
    "GANDERBAL",
    "JAMMU",
    "KATHUA",
    "KUPWARA",
    "PILIBHIT",
    "POONCH",
    "PULWAMA",
    "RAJOURI",
    "RAMBAN",
    "REASI",
    "SAMBA",
    "SHAHJAHANPUR",
    "SHOPIAN",
    "SRINAGAR",
    "UDHAMPUR"
  ],
  "Jharkhand": [
    "AGRA",
    "BOKARO",
    "DEOGHAR",
    "DHANBAD",
    "DUMKA",
    "EAST SINGHBUM",
    "GIRIDIH",
    "GUMLA",
    "HAZARIBAGH",
    "JAMTARA",
    "KHUNTI",
    "KODERMA",
    "LOHARDAGA",
    "PALAMU",
    "PILIBHIT",
    "RANCHI",
    "SIMDEGA"
  ],
  "JHARKHAND": [
    "AGRA",
    "BOKARO",
    "DEOGHAR",
    "DHANBAD",
    "DUMKA",
    "EAST SINGHBUM",
    "GIRIDIH",
    "GUMLA",
    "HAZARIBAGH",
    "JAMTARA",
    "KHUNTI",
    "KODERMA",
    "LOHARDAGA",
    "PALAMU",
    "PILIBHIT",
    "RANCHI",
    "SIMDEGA"
  ],
  "Karnataka": [
    "BAGALKOTE",
    "BALLARI",
    "BELAGAVI",
    "BENGALURU RURAL",
    "BENGALURU SOUTH",
    "BENGALURU URBAN",
    "BIDAR",
    "CHAMARAJANAGAR",
    "CHIKKABALLAPURA",
    "CHIKKAMAGALURU",
    "CHITRADURGA",
    "DAKSHINA KANNADA",
    "DAVANAGERE",
    "DHARWAD",
    "GADAG",
    "HASSAN",
    "HAVERI",
    "KAITHAL",
    "KALABURAGI",
    "KOLAR",
    "KOPPAL",
    "MANDYA",
    "MYSURU",
    "PAKYONG",
    "RAICHUR",
    "SHIVAMOGGA",
    "TUMAKURU",
    "UDUPI",
    "UTTARA KANNADA",
    "YADGIR"
  ],
  "KARNATAKA": [
    "BAGALKOTE",
    "BALLARI",
    "BELAGAVI",
    "BENGALURU RURAL",
    "BENGALURU SOUTH",
    "BENGALURU URBAN",
    "BIDAR",
    "CHAMARAJANAGAR",
    "CHIKKABALLAPURA",
    "CHIKKAMAGALURU",
    "CHITRADURGA",
    "DAKSHINA KANNADA",
    "DAVANAGERE",
    "DHARWAD",
    "GADAG",
    "HASSAN",
    "HAVERI",
    "KAITHAL",
    "KALABURAGI",
    "KOLAR",
    "KOPPAL",
    "MANDYA",
    "MYSURU",
    "PAKYONG",
    "RAICHUR",
    "SHIVAMOGGA",
    "TUMAKURU",
    "UDUPI",
    "UTTARA KANNADA",
    "YADGIR"
  ],
  "Kerala": [
    "ALAPPUZHA",
    "ERNAKULAM",
    "IDUKKI",
    "KANNUR",
    "KASARAGOD",
    "KOLLAM",
    "KOTTAYAM",
    "KOZHIKODE",
    "MALAPPURAM",
    "PALAKKAD",
    "PATHANAMTHITTA",
    "THIRUVANANTHAPURAM",
    "THRISSUR",
    "WAYANAD"
  ],
  "KERALA": [
    "ALAPPUZHA",
    "ERNAKULAM",
    "IDUKKI",
    "KANNUR",
    "KASARAGOD",
    "KOLLAM",
    "KOTTAYAM",
    "KOZHIKODE",
    "MALAPPURAM",
    "PALAKKAD",
    "PATHANAMTHITTA",
    "THIRUVANANTHAPURAM",
    "THRISSUR",
    "WAYANAD"
  ],
  "Ladakh": [
    "LADAKH"
  ],
  "LADAKH": [
    "LADAKH"
  ],
  "Lakshadweep": [
    "LAKSHADWEEP DISTRICT"
  ],
  "LAKSHADWEEP": [
    "LAKSHADWEEP DISTRICT"
  ],
  "Madhya Pradesh": [
    "AGAR-MALWA",
    "AGRA",
    "ALIRAJPUR",
    "ANUPPUR",
    "ASHOKNAGAR",
    "BALAGHAT",
    "BARWANI",
    "BETUL",
    "BHIND",
    "BHOPAL",
    "BURHANPUR",
    "CHHATARPUR",
    "CHHINDWARA",
    "DAMOH",
    "DATIA",
    "DEWAS",
    "DHAR",
    "GUNA",
    "GWALIOR",
    "INDORE",
    "JABALPUR",
    "JHABUA",
    "KAITHAL",
    "KATNI",
    "KHANDWA",
    "KHARGONE",
    "MAIHAR",
    "MANDLA",
    "MANDSAUR",
    "MAUGANJ",
    "MORENA",
    "NARMADAPURAM",
    "NARSIMHAPUR",
    "NEEMUCH",
    "PANDHURNA",
    "PANNA",
    "PILIBHIT",
    "RAJGARH",
    "RATLAM",
    "SAGAR",
    "SATNA",
    "SEHORE",
    "SEONI",
    "SHAHDOL",
    "SHAJAPUR",
    "SHEOPUR",
    "SHIVPURI",
    "SIDHI",
    "SINGRAULI",
    "TIKAMGARH",
    "UJJAIN",
    "VIDISHA"
  ],
  "MADHYA PRADESH": [
    "AGAR-MALWA",
    "AGRA",
    "ALIRAJPUR",
    "ANUPPUR",
    "ASHOKNAGAR",
    "BALAGHAT",
    "BARWANI",
    "BETUL",
    "BHIND",
    "BHOPAL",
    "BURHANPUR",
    "CHHATARPUR",
    "CHHINDWARA",
    "DAMOH",
    "DATIA",
    "DEWAS",
    "DHAR",
    "GUNA",
    "GWALIOR",
    "INDORE",
    "JABALPUR",
    "JHABUA",
    "KAITHAL",
    "KATNI",
    "KHANDWA",
    "KHARGONE",
    "MAIHAR",
    "MANDLA",
    "MANDSAUR",
    "MAUGANJ",
    "MORENA",
    "NARMADAPURAM",
    "NARSIMHAPUR",
    "NEEMUCH",
    "PANDHURNA",
    "PANNA",
    "PILIBHIT",
    "RAJGARH",
    "RATLAM",
    "SAGAR",
    "SATNA",
    "SEHORE",
    "SEONI",
    "SHAHDOL",
    "SHAJAPUR",
    "SHEOPUR",
    "SHIVPURI",
    "SIDHI",
    "SINGRAULI",
    "TIKAMGARH",
    "UJJAIN",
    "VIDISHA"
  ],
  "Maharashtra": [
    "AHILYANAGAR",
    "AKOLA",
    "AMRAVATI",
    "BEED",
    "BHANDARA",
    "BULDHANA",
    "CHANDRAPUR",
    "CHHATRAPATI SAMBHAJINAGAR",
    "DHARASHIV",
    "DHULE",
    "ETAH",
    "GADCHIROLI",
    "GONDIA",
    "GOPALGANJ",
    "HINGOLI",
    "JALGAON",
    "KOLHAPUR",
    "KUPWARA",
    "LATUR",
    "MUMBAI",
    "NAGPUR",
    "NANDED",
    "NASHIK",
    "PAKYONG",
    "PALGHAR",
    "PARBHANI",
    "PUNE",
    "PURBI CHAMPARAN",
    "RAIGAD",
    "RATNAGIRI",
    "SAHARSA",
    "SANGLI",
    "SATARA",
    "SINDHUDURG",
    "SOLAPUR",
    "THANE",
    "TUMAKURU",
    "WARDHA",
    "WASHIM",
    "YAVATMAL"
  ],
  "MAHARASHTRA": [
    "AHILYANAGAR",
    "AKOLA",
    "AMRAVATI",
    "BEED",
    "BHANDARA",
    "BULDHANA",
    "CHANDRAPUR",
    "CHHATRAPATI SAMBHAJINAGAR",
    "DHARASHIV",
    "DHULE",
    "ETAH",
    "GADCHIROLI",
    "GONDIA",
    "GOPALGANJ",
    "HINGOLI",
    "JALGAON",
    "KOLHAPUR",
    "KUPWARA",
    "LATUR",
    "MUMBAI",
    "NAGPUR",
    "NANDED",
    "NASHIK",
    "PAKYONG",
    "PALGHAR",
    "PARBHANI",
    "PUNE",
    "PURBI CHAMPARAN",
    "RAIGAD",
    "RATNAGIRI",
    "SAHARSA",
    "SANGLI",
    "SATARA",
    "SINDHUDURG",
    "SOLAPUR",
    "THANE",
    "TUMAKURU",
    "WARDHA",
    "WASHIM",
    "YAVATMAL"
  ],
  "Manipur": [
    "CHURACHANDPUR",
    "IMPHAL EAST",
    "IMPHAL WEST",
    "KAKCHING",
    "THOUBAL"
  ],
  "MANIPUR": [
    "CHURACHANDPUR",
    "IMPHAL EAST",
    "IMPHAL WEST",
    "KAKCHING",
    "THOUBAL"
  ],
  "Meghalaya": [
    "EAST JAINTIA HILLS",
    "EAST KHASI HILLS",
    "EASTERN WEST KHASI HILLS",
    "RI BHOI",
    "SOUTH GARO HILLS",
    "SOUTH WEST KHASI HILLS",
    "WEST GARO HILLS",
    "WEST JAINTIA HILLS",
    "WEST KHASI HILLS"
  ],
  "MEGHALAYA": [
    "EAST JAINTIA HILLS",
    "EAST KHASI HILLS",
    "EASTERN WEST KHASI HILLS",
    "RI BHOI",
    "SOUTH GARO HILLS",
    "SOUTH WEST KHASI HILLS",
    "WEST GARO HILLS",
    "WEST JAINTIA HILLS",
    "WEST KHASI HILLS"
  ],
  "Mizoram": [
    "AIZAWL",
    "CHAMPHAI",
    "KHAWZAWL",
    "KOLASIB",
    "LUNGLEI",
    "SAITUAL",
    "SERCHHIP",
    "SIAHA"
  ],
  "MIZORAM": [
    "AIZAWL",
    "CHAMPHAI",
    "KHAWZAWL",
    "KOLASIB",
    "LUNGLEI",
    "SAITUAL",
    "SERCHHIP",
    "SIAHA"
  ],
  "Nagaland": [
    "CHUMOUKEDIMA",
    "DIMAPUR",
    "KIPHIRE",
    "KOHIMA",
    "MOKOKCHUNG",
    "MON",
    "NOKLAK",
    "PEREN",
    "PHEK",
    "TSEMINYU",
    "TUENSANG",
    "WOKHA"
  ],
  "NAGALAND": [
    "CHUMOUKEDIMA",
    "DIMAPUR",
    "KIPHIRE",
    "KOHIMA",
    "MOKOKCHUNG",
    "MON",
    "NOKLAK",
    "PEREN",
    "PHEK",
    "TSEMINYU",
    "TUENSANG",
    "WOKHA"
  ],
  "Odisha": [
    "BALANGIR",
    "BALESHWAR",
    "BARAGADA",
    "BHADRAK",
    "GAJAPATI",
    "GANJAM",
    "JAGATSINGHAPUR",
    "JAJPUR",
    "KALAHANDI",
    "KANDHAMALA",
    "KATAKA",
    "KENDRAPADA",
    "KENDUJHAR",
    "KHORDHA",
    "KORAPUT",
    "MALKANGIRI",
    "MAYURBHANJ",
    "NABARANGPUR",
    "NAYAGADA",
    "NUAPADA",
    "PURI",
    "RAYAGADA",
    "SAMBALPUR",
    "SUBARNAPUR",
    "SUNDARAGADA"
  ],
  "ODISHA": [
    "BALANGIR",
    "BALESHWAR",
    "BARAGADA",
    "BHADRAK",
    "GAJAPATI",
    "GANJAM",
    "JAGATSINGHAPUR",
    "JAJPUR",
    "KALAHANDI",
    "KANDHAMALA",
    "KATAKA",
    "KENDRAPADA",
    "KENDUJHAR",
    "KHORDHA",
    "KORAPUT",
    "MALKANGIRI",
    "MAYURBHANJ",
    "NABARANGPUR",
    "NAYAGADA",
    "NUAPADA",
    "PURI",
    "RAYAGADA",
    "SAMBALPUR",
    "SUBARNAPUR",
    "SUNDARAGADA"
  ],
  "Puducherry": [
    "PUDUCHERRY",
    "TIRUVANNAMALAI"
  ],
  "PUDUCHERRY": [
    "PUDUCHERRY",
    "TIRUVANNAMALAI"
  ],
  "Punjab": [
    "AMRITSAR",
    "BARNALA",
    "BATHINDA",
    "CHANDIGARH",
    "FARIDKOT",
    "FATEHGARH SAHIB",
    "FAZILKA",
    "FEROZEPUR",
    "GURDASPUR",
    "HOSHIARPUR",
    "JALANDHAR",
    "KAPURTHALA",
    "LUDHIANA",
    "MALERKOTLA",
    "MANSA",
    "MOGA",
    "PATHANKOT",
    "PATIALA",
    "RUPNAGAR",
    "S.A.S NAGAR",
    "SANGRUR",
    "SHAHID BHAGAT SINGH NAGAR",
    "SRI MUKTSAR SAHIB",
    "TARN TARAN"
  ],
  "PUNJAB": [
    "AMRITSAR",
    "BARNALA",
    "BATHINDA",
    "CHANDIGARH",
    "FARIDKOT",
    "FATEHGARH SAHIB",
    "FAZILKA",
    "FEROZEPUR",
    "GURDASPUR",
    "HOSHIARPUR",
    "JALANDHAR",
    "KAPURTHALA",
    "LUDHIANA",
    "MALERKOTLA",
    "MANSA",
    "MOGA",
    "PATHANKOT",
    "PATIALA",
    "RUPNAGAR",
    "S.A.S NAGAR",
    "SANGRUR",
    "SHAHID BHAGAT SINGH NAGAR",
    "SRI MUKTSAR SAHIB",
    "TARN TARAN"
  ],
  "Rajasthan": [
    "AJMER",
    "ALWAR",
    "BALOTRA",
    "BANSWARA",
    "BARMER",
    "BEAWAR",
    "BHARATPUR",
    "BHILWARA",
    "BIKANER",
    "BUNDI",
    "CHITTORGARH",
    "CHURU",
    "DAUSA",
    "DEEG",
    "DHOLPUR",
    "DIDWANA-KUCHAMAN",
    "DUDU",
    "DUNGARPUR",
    "GANGANAGAR",
    "GANGAPURCITY",
    "HANUMANGARH",
    "JAIPUR",
    "JAIPUR GRAMIN",
    "JAISALMER",
    "JALORE",
    "JHUNJHUNU",
    "JODHPUR",
    "JODHPUR GRAMIN",
    "KAITHAL",
    "KARAULI",
    "KEKRI",
    "KHAIRTHAL-TIJARA",
    "KOTA",
    "KOTPUTLI-BEHROR",
    "NAGAUR",
    "NEEM KA THANA",
    "PALI",
    "PHALODI",
    "PILIBHIT",
    "PRATAPGARH",
    "RAJSAMAND",
    "SALUMBAR",
    "SANCHOR",
    "SHAHJAHANPUR",
    "SHAHPURA",
    "SIKAR",
    "SIROHI",
    "UDAIPUR"
  ],
  "RAJASTHAN": [
    "AJMER",
    "ALWAR",
    "BALOTRA",
    "BANSWARA",
    "BARMER",
    "BEAWAR",
    "BHARATPUR",
    "BHILWARA",
    "BIKANER",
    "BUNDI",
    "CHITTORGARH",
    "CHURU",
    "DAUSA",
    "DEEG",
    "DHOLPUR",
    "DIDWANA-KUCHAMAN",
    "DUDU",
    "DUNGARPUR",
    "GANGANAGAR",
    "GANGAPURCITY",
    "HANUMANGARH",
    "JAIPUR",
    "JAIPUR GRAMIN",
    "JAISALMER",
    "JALORE",
    "JHUNJHUNU",
    "JODHPUR",
    "JODHPUR GRAMIN",
    "KAITHAL",
    "KARAULI",
    "KEKRI",
    "KHAIRTHAL-TIJARA",
    "KOTA",
    "KOTPUTLI-BEHROR",
    "NAGAUR",
    "NEEM KA THANA",
    "PALI",
    "PHALODI",
    "PILIBHIT",
    "PRATAPGARH",
    "RAJSAMAND",
    "SALUMBAR",
    "SANCHOR",
    "SHAHJAHANPUR",
    "SHAHPURA",
    "SIKAR",
    "SIROHI",
    "UDAIPUR"
  ],
  "Sikkim": [
    "GANGTOK",
    "GYALSHING",
    "MANGAN",
    "PAKYONG",
    "SORENG"
  ],
  "SIKKIM": [
    "GANGTOK",
    "GYALSHING",
    "MANGAN",
    "PAKYONG",
    "SORENG"
  ],
  "Tamil Nadu": [
    "ARIYALUR",
    "CHENGALPATTU",
    "CHENNAI",
    "COIMBATORE",
    "CUDDALORE",
    "DHARMAPURI",
    "DINDIGUL",
    "ERODE",
    "KALLAKURICHI",
    "KANCHEEPURAM",
    "KANNIYAKUMARI",
    "KARUR",
    "KRISHNAGIRI",
    "MADURAI",
    "MAYILADUTHURAI",
    "NAGAPATTINAM",
    "NAMAKKAL",
    "PERAMBALUR",
    "PUDUKKOTTAI",
    "RAMANATHAPURAM",
    "RANIPET",
    "SALEM",
    "SIVAGANGA",
    "TENKASI",
    "THANJAVUR",
    "THE NILGIRIS",
    "THENI",
    "THIRUVALLUR",
    "THIRUVARUR",
    "THOOTHUKKUDI",
    "TIRUCHIRAPPALLI",
    "TIRUNELVELI",
    "TIRUPATHUR",
    "TIRUPPUR",
    "TIRUVANNAMALAI",
    "VELLORE",
    "VILUPPURAM",
    "VIRUDHUNAGAR"
  ],
  "TAMIL NADU": [
    "ARIYALUR",
    "CHENGALPATTU",
    "CHENNAI",
    "COIMBATORE",
    "CUDDALORE",
    "DHARMAPURI",
    "DINDIGUL",
    "ERODE",
    "KALLAKURICHI",
    "KANCHEEPURAM",
    "KANNIYAKUMARI",
    "KARUR",
    "KRISHNAGIRI",
    "MADURAI",
    "MAYILADUTHURAI",
    "NAGAPATTINAM",
    "NAMAKKAL",
    "PERAMBALUR",
    "PUDUKKOTTAI",
    "RAMANATHAPURAM",
    "RANIPET",
    "SALEM",
    "SIVAGANGA",
    "TENKASI",
    "THANJAVUR",
    "THE NILGIRIS",
    "THENI",
    "THIRUVALLUR",
    "THIRUVARUR",
    "THOOTHUKKUDI",
    "TIRUCHIRAPPALLI",
    "TIRUNELVELI",
    "TIRUPATHUR",
    "TIRUPPUR",
    "TIRUVANNAMALAI",
    "VELLORE",
    "VILUPPURAM",
    "VIRUDHUNAGAR"
  ],
  "Telangana": [
    "ADILABAD",
    "BHADRADRI KOTHAGUDEM",
    "HANUMAKONDA",
    "HYDERABAD",
    "JAGITIAL",
    "JANGOAN",
    "JAYASHANKAR BHUPALAPALLY",
    "JOGULAMBA GADWAL",
    "KAITHAL",
    "KAMAREDDY",
    "KARIMNAGAR",
    "KHAMMAM",
    "KUMURAM BHEEM ASIFABAD",
    "MAHABUBABAD",
    "MAHABUBNAGAR",
    "MANCHERIAL",
    "MEDAK",
    "MEDCHAL MALKAJGIRI",
    "MULUGU",
    "NAGARKURNOOL",
    "NALGONDA",
    "NARAYANPET",
    "NIRMAL",
    "NIZAMABAD",
    "PEDDAPALLI",
    "RAJANNA SIRCILLA",
    "RANGA REDDY",
    "SANGAREDDY",
    "SIDDIPET",
    "SURYAPET",
    "VIKARABAD",
    "WANAPARTHY",
    "WARANGAL",
    "YADADRI BHUVANAGIRI"
  ],
  "TELANGANA": [
    "ADILABAD",
    "BHADRADRI KOTHAGUDEM",
    "HANUMAKONDA",
    "HYDERABAD",
    "JAGITIAL",
    "JANGOAN",
    "JAYASHANKAR BHUPALAPALLY",
    "JOGULAMBA GADWAL",
    "KAITHAL",
    "KAMAREDDY",
    "KARIMNAGAR",
    "KHAMMAM",
    "KUMURAM BHEEM ASIFABAD",
    "MAHABUBABAD",
    "MAHABUBNAGAR",
    "MANCHERIAL",
    "MEDAK",
    "MEDCHAL MALKAJGIRI",
    "MULUGU",
    "NAGARKURNOOL",
    "NALGONDA",
    "NARAYANPET",
    "NIRMAL",
    "NIZAMABAD",
    "PEDDAPALLI",
    "RAJANNA SIRCILLA",
    "RANGA REDDY",
    "SANGAREDDY",
    "SIDDIPET",
    "SURYAPET",
    "VIKARABAD",
    "WANAPARTHY",
    "WARANGAL",
    "YADADRI BHUVANAGIRI"
  ],
  "The Dadra And Nagar Haveli And Daman And Diu": [
    "DADRA & NAGAR HAVELI",
    "DAMAN and DIU"
  ],
  "THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU": [
    "DADRA & NAGAR HAVELI",
    "DAMAN and DIU"
  ],
  "Tripura": [
    "KHOWAI",
    "SEPAHIJALA",
    "WEST TRIPURA"
  ],
  "TRIPURA": [
    "KHOWAI",
    "SEPAHIJALA",
    "WEST TRIPURA"
  ],
  "Uttar Pradesh": [
    "AGRA",
    "ALIGARH",
    "AMBEDKAR NAGAR",
    "AMETHI",
    "AMROHA",
    "AURAIYA",
    "AYODHYA",
    "AZAMGARH",
    "BAGHPAT",
    "BAHRAICH",
    "BALLIA",
    "BALRAMPUR",
    "BANDA",
    "BARA BANKI",
    "BAREILLY",
    "BASTI",
    "BHADOHI",
    "BIJNOR",
    "BUDAUN",
    "BULANDSHAHR",
    "CHANDAULI",
    "DEORIA",
    "ETAH",
    "ETAWAH",
    "FARRUKHABAD",
    "FATEHPUR",
    "FIROZABAD",
    "GAUTAM BUDDHA NAGAR",
    "GHAZIABAD",
    "GHAZIPUR",
    "GONDA",
    "GORAKHPUR",
    "HAMIRPUR",
    "HAPUR",
    "HARDOI",
    "HATHRAS",
    "JAUNPUR",
    "JHANSI",
    "KANNAUJ",
    "KANPUR DEHAT",
    "KANPUR NAGAR",
    "KASGANJ",
    "KAUSHAMBI",
    "KHERI",
    "KUSHINAGAR",
    "LALITPUR",
    "LUCKNOW",
    "MAHOBA",
    "MAHRAJGANJ",
    "MAINPURI",
    "MATHURA",
    "MAU",
    "MEERUT",
    "MIRZAPUR",
    "MORADABAD",
    "MUZAFFARNAGAR",
    "PATHANAMTHITTA",
    "PHEK",
    "PILIBHIT",
    "PRATAPGARH",
    "PRAYAGRAJ",
    "RAE BARELI",
    "RAMPUR",
    "SAHARANPUR",
    "SAMBHAL",
    "SANT KABIR NAGAR",
    "SHAHJAHANPUR",
    "SHAMLI",
    "SIDDHARTHNAGAR",
    "SITAPUR",
    "SONBHADRA",
    "SULTANPUR",
    "UNNAO",
    "VARANASI"
  ],
  "UTTAR PRADESH": [
    "AGRA",
    "ALIGARH",
    "AMBEDKAR NAGAR",
    "AMETHI",
    "AMROHA",
    "AURAIYA",
    "AYODHYA",
    "AZAMGARH",
    "BAGHPAT",
    "BAHRAICH",
    "BALLIA",
    "BALRAMPUR",
    "BANDA",
    "BARA BANKI",
    "BAREILLY",
    "BASTI",
    "BHADOHI",
    "BIJNOR",
    "BUDAUN",
    "BULANDSHAHR",
    "CHANDAULI",
    "DEORIA",
    "ETAH",
    "ETAWAH",
    "FARRUKHABAD",
    "FATEHPUR",
    "FIROZABAD",
    "GAUTAM BUDDHA NAGAR",
    "GHAZIABAD",
    "GHAZIPUR",
    "GONDA",
    "GORAKHPUR",
    "HAMIRPUR",
    "HAPUR",
    "HARDOI",
    "HATHRAS",
    "JAUNPUR",
    "JHANSI",
    "KANNAUJ",
    "KANPUR DEHAT",
    "KANPUR NAGAR",
    "KASGANJ",
    "KAUSHAMBI",
    "KHERI",
    "KUSHINAGAR",
    "LALITPUR",
    "LUCKNOW",
    "MAHOBA",
    "MAHRAJGANJ",
    "MAINPURI",
    "MATHURA",
    "MAU",
    "MEERUT",
    "MIRZAPUR",
    "MORADABAD",
    "MUZAFFARNAGAR",
    "PATHANAMTHITTA",
    "PHEK",
    "PILIBHIT",
    "PRATAPGARH",
    "PRAYAGRAJ",
    "RAE BARELI",
    "RAMPUR",
    "SAHARANPUR",
    "SAMBHAL",
    "SANT KABIR NAGAR",
    "SHAHJAHANPUR",
    "SHAMLI",
    "SIDDHARTHNAGAR",
    "SITAPUR",
    "SONBHADRA",
    "SULTANPUR",
    "UNNAO",
    "VARANASI"
  ],
  "Uttarakhand": [
    "AGRA",
    "ALMORA",
    "BAGESHWAR",
    "CHAMOLI",
    "DEHRADUN",
    "HARIDWAR",
    "KARNAL",
    "NAINITAL",
    "PAURI GARHWAL",
    "PITHORAGARH",
    "RUDRAPRAYAG",
    "TEHRI GARHWAL",
    "UDHAM SINGH NAGAR",
    "UTTARKASHI"
  ],
  "UTTARAKHAND": [
    "AGRA",
    "ALMORA",
    "BAGESHWAR",
    "CHAMOLI",
    "DEHRADUN",
    "HARIDWAR",
    "KARNAL",
    "NAINITAL",
    "PAURI GARHWAL",
    "PITHORAGARH",
    "RUDRAPRAYAG",
    "TEHRI GARHWAL",
    "UDHAM SINGH NAGAR",
    "UTTARKASHI"
  ],
  "West Bengal": [
    "BANKURA",
    "BIRBHUM",
    "COOCH BEHAR",
    "DAKSHIN DINAJPUR",
    "DARJEELING",
    "HOOGHLY",
    "HOWRAH",
    "JALPAIGURI",
    "JHARGRAM",
    "KALIMPONG",
    "KOLKATA",
    "MALDA",
    "MURSHIDABAD",
    "NADIA",
    "NORTH 24 PARGANAS",
    "PASCHIM BARDHAMAN",
    "PASCHIM MEDINIPUR",
    "PURBA BARDHAMAN",
    "PURBA MEDINIPUR",
    "PURULIA",
    "SOUTH 24 PARGANAS",
    "UTTAR DINAJPUR"
  ],
  "WEST BENGAL": [
    "BANKURA",
    "BIRBHUM",
    "COOCH BEHAR",
    "DAKSHIN DINAJPUR",
    "DARJEELING",
    "HOOGHLY",
    "HOWRAH",
    "JALPAIGURI",
    "JHARGRAM",
    "KALIMPONG",
    "KOLKATA",
    "MALDA",
    "MURSHIDABAD",
    "NADIA",
    "NORTH 24 PARGANAS",
    "PASCHIM BARDHAMAN",
    "PASCHIM MEDINIPUR",
    "PURBA BARDHAMAN",
    "PURBA MEDINIPUR",
    "PURULIA",
    "SOUTH 24 PARGANAS",
    "UTTAR DINAJPUR"
  ]
};
