"""
Canonical Database Models for MPLADS Fraud Detection System.
Compatible with PostgreSQL (production) and SQLite (embedded testing).
"""

import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    Column, Integer, Float, String, Text, Date, DateTime, Boolean,
    ForeignKey, UniqueConstraint, CheckConstraint, Index, JSON
)
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


class PipelineRun(Base):
    """Tracks snapshot execution runs with atomic status management."""
    __tablename__ = "pipeline_runs"

    run_id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    run_key = Column(String(100), nullable=False, index=True)
    started_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    completed_at = Column(DateTime, nullable=True)
    status = Column(String(20), default="RUNNING", nullable=False)
    error_message = Column(Text, nullable=True)

    anomalies = relationship("Anomaly", back_populates="pipeline_run", cascade="all, delete-orphan")
    review_items = relationship("ReviewQueueItem", back_populates="pipeline_run", cascade="all, delete-orphan")
    entity_risks = relationship("EntityRisk", back_populates="pipeline_run", cascade="all, delete-orphan")


class Work(Base):
    """Canonical Single-Source-of-Truth for all MPLADS Infrastructure Works."""
    __tablename__ = "works"

    work_id = Column(Integer, primary_key=True)
    work_description = Column(Text, nullable=False)
    cost = Column(Float, nullable=False)
    category = Column(String(100), nullable=True, index=True)
    location = Column(Text, nullable=True)
    district = Column(String(100), nullable=False, index=True)
    mp_name = Column(String(200), nullable=False, index=True)
    mp_constituency = Column(String(100), nullable=True, index=True)
    completion_date = Column(Date, nullable=True, index=True)
    recommended_date = Column(Date, nullable=True, index=True)
    status = Column(String(50), default="completed", nullable=False, index=True)
    has_payments = Column(Boolean, default=False, nullable=False)
    total_paid = Column(Float, default=0.0, nullable=False)
    payment_gap_percentage = Column(Float, default=0.0, nullable=True)
    payment_record_exists = Column(Boolean, default=False, nullable=False)
    house = Column(String(50), nullable=True)
    ls_term = Column(String(50), nullable=True)
    state = Column(String(100), default="ANDHRA PRADESH", nullable=True)

    anomalies = relationship("Anomaly", back_populates="work", cascade="all, delete-orphan")

    __table_args__ = (
        CheckConstraint("cost > 0", name="chk_positive_cost"),
        Index("idx_works_district_date", "district", "completion_date"),
        Index("idx_works_mp_date", "mp_name", "recommended_date"),
    )


class Anomaly(Base):
    """Deduplicated Forensic Anomaly Records generated by Detectors D1-D12, D15."""
    __tablename__ = "anomalies"

    anomaly_id = Column(Integer, primary_key=True, autoincrement=True)
    work_id = Column(Integer, ForeignKey("works.work_id", ondelete="CASCADE"), nullable=False, index=True)
    detector_type = Column(String(50), nullable=False, index=True)
    severity = Column(Float, nullable=False, index=True)
    explanation = Column(Text, nullable=False)
    evidence = Column(JSON, nullable=False)
    run_id = Column(String(36), ForeignKey("pipeline_runs.run_id", ondelete="CASCADE"), nullable=False, index=True)
    detected_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    work = relationship("Work", back_populates="anomalies")
    pipeline_run = relationship("PipelineRun", back_populates="anomalies")

    __table_args__ = (
        UniqueConstraint("work_id", "detector_type", "run_id", name="uq_work_detector_run"),
        CheckConstraint("severity >= 0.50 AND severity <= 1.00", name="chk_valid_anomaly_severity"),
        Index("idx_anomalies_composite", "detector_type", "severity"),
    )


class ReviewQueueItem(Base):
    """Borderline Case Review Queue for D2 & content similarity flags."""
    __tablename__ = "review_queue"

    review_id = Column(Integer, primary_key=True, autoincrement=True)
    work_id_a = Column(Integer, ForeignKey("works.work_id", ondelete="CASCADE"), nullable=False)
    work_id_b = Column(Integer, ForeignKey("works.work_id", ondelete="CASCADE"), nullable=False)
    detector_type = Column(String(50), nullable=False)
    similarity = Column(Float, nullable=False)
    reason = Column(Text, nullable=False)
    status = Column(String(20), default="PENDING", nullable=False)
    run_id = Column(String(36), ForeignKey("pipeline_runs.run_id", ondelete="CASCADE"), nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    pipeline_run = relationship("PipelineRun", back_populates="review_items")

    __table_args__ = (
        UniqueConstraint("work_id_a", "work_id_b", "detector_type", "run_id", name="uq_review_pair_run"),
        CheckConstraint("work_id_a < work_id_b", name="chk_canonical_pair_order"),
        Index("idx_review_queue_run_status", "run_id", "status"),
    )


class EntityRisk(Base):
    """Forensic Risk Profiles for Implementing District Authorities (IDAs) and MPs (D13, D14)."""
    __tablename__ = "entity_risks"

    entity_type = Column(String(20), primary_key=True)  # 'ida', 'mp', 'constituency'
    entity_key = Column(String(200), primary_key=True)
    run_id = Column(String(36), ForeignKey("pipeline_runs.run_id", ondelete="CASCADE"), primary_key=True)
    composite_risk = Column(Float, nullable=False)      # 0.0 - 100.0
    risk_tier = Column(String(20), nullable=False)      # 'Clean', 'Medium', 'High', 'Very High', 'Critical'
    risk_rank = Column(Integer, nullable=False)
    breakdown = Column(JSON, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    pipeline_run = relationship("PipelineRun", back_populates="entity_risks")

    __table_args__ = (
        Index("idx_entity_risk_rank", "entity_type", "risk_rank"),
    )
