"""Initial schema with lineage, rbac, and core models

Revision ID: 35fc48c5955e
Revises: 
Create Date: 2026-09-02 23:31:14.465227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35fc48c5955e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('contractor_id', sa.String(length=50), nullable=False),
    sa.Column('contractor_name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('bank_account_hash', sa.String(length=64), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('contractor_id')
    )
    op.create_index(op.f('ix_contractors_contractor_name'), 'contractors', ['contractor_name'], unique=False)
    op.create_index(op.f('ix_contractors_gstin'), 'contractors', ['gstin'], unique=False)
    op.create_table('datasets',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('source_organization', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('file_checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('data_origin', sa.String(length=50), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_index(op.f('ix_datasets_file_checksum_sha256'), 'datasets', ['file_checksum_sha256'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('git_commit_hash', sa.String(length=40), nullable=True),
    sa.Column('etl_version', sa.String(length=20), nullable=True),
    sa.Column('raw_row_count', sa.Integer(), nullable=True),
    sa.Column('valid_row_count', sa.Integer(), nullable=True),
    sa.Column('duplicate_row_count', sa.Integer(), nullable=True),
    sa.Column('rejected_row_count', sa.Integer(), nullable=True),
    sa.Column('reconciliation_summary', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('run_key', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_pipeline_runs_run_key'), 'pipeline_runs', ['run_key'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('entity_risks',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_key', sa.String(length=200), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('composite_risk', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.String(length=20), nullable=False),
    sa.Column('risk_rank', sa.Integer(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_type', 'entity_key', 'run_id')
    )
    op.create_index('idx_entity_risk_rank', 'entity_risks', ['entity_type', 'risk_rank'], unique=False)
    op.create_table('works',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('work_description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('mp_name', sa.String(length=200), nullable=False),
    sa.Column('mp_constituency', sa.String(length=100), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('recommended_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('has_payments', sa.Boolean(), nullable=False),
    sa.Column('total_paid', sa.Float(), nullable=False),
    sa.Column('payment_gap_percentage', sa.Float(), nullable=True),
    sa.Column('payment_record_exists', sa.Boolean(), nullable=False),
    sa.Column('house', sa.String(length=50), nullable=True),
    sa.Column('ls_term', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_file_checksum', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('etl_version', sa.String(length=20), nullable=True),
    sa.Column('data_origin', sa.String(length=50), nullable=False),
    sa.Column('data_quality_status', sa.String(length=20), nullable=True),
    sa.Column('payment_data_status', sa.String(length=30), nullable=True),
    sa.Column('data_completeness_score', sa.Float(), nullable=True),
    sa.Column('source_dataset_id', sa.String(length=36), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('cost > 0', name='chk_positive_cost'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.run_id'], ),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['datasets.dataset_id'], ),
    sa.PrimaryKeyConstraint('work_id')
    )
    op.create_index('idx_works_district_date', 'works', ['district', 'completion_date'], unique=False)
    op.create_index('idx_works_mp_date', 'works', ['mp_name', 'recommended_date'], unique=False)
    op.create_index(op.f('ix_works_category'), 'works', ['category'], unique=False)
    op.create_index(op.f('ix_works_completion_date'), 'works', ['completion_date'], unique=False)
    op.create_index(op.f('ix_works_district'), 'works', ['district'], unique=False)
    op.create_index(op.f('ix_works_mp_constituency'), 'works', ['mp_constituency'], unique=False)
    op.create_index(op.f('ix_works_mp_name'), 'works', ['mp_name'], unique=False)
    op.create_index(op.f('ix_works_recommended_date'), 'works', ['recommended_date'], unique=False)
    op.create_index(op.f('ix_works_status'), 'works', ['status'], unique=False)
    op.create_table('anomalies',
    sa.Column('anomaly_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('detector_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('severity >= 0.50 AND severity <= 1.00', name='chk_valid_anomaly_severity'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anomaly_id'),
    sa.UniqueConstraint('work_id', 'detector_type', 'run_id', name='uq_work_detector_run')
    )
    op.create_index('idx_anomalies_composite', 'anomalies', ['detector_type', 'severity'], unique=False)
    op.create_index(op.f('ix_anomalies_detector_type'), 'anomalies', ['detector_type'], unique=False)
    op.create_index(op.f('ix_anomalies_run_id'), 'anomalies', ['run_id'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.create_index(op.f('ix_anomalies_work_id'), 'anomalies', ['work_id'], unique=False)
    op.create_table('audit_outcomes',
    sa.Column('audit_id', sa.String(length=50), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('audit_date', sa.Date(), nullable=False),
    sa.Column('auditor_organization', sa.String(length=100), nullable=True),
    sa.Column('audit_type', sa.String(length=50), nullable=True),
    sa.Column('finding_category', sa.String(length=50), nullable=True),
    sa.Column('fraud_confirmed', sa.Boolean(), nullable=True),
    sa.Column('recovery_amount', sa.Float(), nullable=True),
    sa.Column('recovery_order_number', sa.String(length=50), nullable=True),
    sa.Column('prosecution_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_outcomes_fraud_confirmed'), 'audit_outcomes', ['fraud_confirmed'], unique=False)
    op.create_index(op.f('ix_audit_outcomes_work_id'), 'audit_outcomes', ['work_id'], unique=False)
    op.create_table('complaints',
    sa.Column('complaint_id', sa.String(length=50), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('complaint_date', sa.Date(), nullable=False),
    sa.Column('complainant_type', sa.String(length=50), nullable=True),
    sa.Column('complaint_category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index(op.f('ix_complaints_work_id'), 'complaints', ['work_id'], unique=False)
    op.create_table('geotagged_photos',
    sa.Column('photo_id', sa.String(length=50), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('photo_date', sa.Date(), nullable=True),
    sa.Column('photo_stage', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('photo_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_index(op.f('ix_geotagged_photos_work_id'), 'geotagged_photos', ['work_id'], unique=False)
    op.create_table('inspections',
    sa.Column('inspection_id', sa.String(length=50), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('inspection_type', sa.String(length=50), nullable=True),
    sa.Column('inspector_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inspection_id')
    )
    op.create_index(op.f('ix_inspections_work_id'), 'inspections', ['work_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.String(length=50), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('invoice_amount', sa.Float(), nullable=False),
    sa.Column('quantity_billed', sa.Float(), nullable=True),
    sa.Column('unit_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_invoices_work_id'), 'invoices', ['work_id'], unique=False)
    op.create_table('measurement_books',
    sa.Column('mb_id', sa.String(length=50), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('mb_date', sa.Date(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('quantity_measured', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('engineer_name', sa.String(length=255), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mb_id')
    )
    op.create_index(op.f('ix_measurement_books_work_id'), 'measurement_books', ['work_id'], unique=False)
    op.create_table('payment_vouchers',
    sa.Column('voucher_id', sa.String(length=50), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.String(length=50), nullable=True),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('invoice_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.contractor_id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voucher_id')
    )
    op.create_index(op.f('ix_payment_vouchers_contractor_id'), 'payment_vouchers', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_payment_vouchers_voucher_date'), 'payment_vouchers', ['voucher_date'], unique=False)
    op.create_index(op.f('ix_payment_vouchers_work_id'), 'payment_vouchers', ['work_id'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.String(length=50), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('fraud_probability', sa.Float(), nullable=False),
    sa.Column('confidence_interval_lower', sa.Float(), nullable=False),
    sa.Column('confidence_interval_upper', sa.Float(), nullable=False),
    sa.Column('uncertainty_score', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_predictions_fraud_probability'), 'predictions', ['fraud_probability'], unique=False)
    op.create_index(op.f('ix_predictions_run_id'), 'predictions', ['run_id'], unique=False)
    op.create_index(op.f('ix_predictions_work_id'), 'predictions', ['work_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id_a', sa.Integer(), nullable=False),
    sa.Column('work_id_b', sa.Integer(), nullable=False),
    sa.Column('detector_type', sa.String(length=50), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id_a'], ['works.work_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id_b'], ['works.work_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('tenders',
    sa.Column('tender_id', sa.String(length=50), nullable=False),
    sa.Column('tender_package_id', sa.String(length=50), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('tender_date', sa.Date(), nullable=True),
    sa.Column('award_date', sa.Date(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('awarded_cost', sa.Float(), nullable=True),
    sa.Column('bidder_count', sa.Integer(), nullable=True),
    sa.Column('procurement_method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tender_id')
    )
    op.create_index(op.f('ix_tenders_tender_package_id'), 'tenders', ['tender_package_id'], unique=False)
    op.create_index(op.f('ix_tenders_work_id'), 'tenders', ['work_id'], unique=False)
    op.create_table('bidders',
    sa.Column('bidder_id', sa.String(length=50), nullable=False),
    sa.Column('tender_id', sa.String(length=50), nullable=False),
    sa.Column('bidder_name', sa.String(length=255), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.tender_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bidder_id')
    )
    op.create_index(op.f('ix_bidders_tender_id'), 'bidders', ['tender_id'], unique=False)
    op.create_table('fraud_labels',
    sa.Column('label_id', sa.String(length=50), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('label_class', sa.String(length=50), nullable=False),
    sa.Column('label_date', sa.Date(), nullable=False),
    sa.Column('labeler_id', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('evidence_documents', sa.JSON(), nullable=True),
    sa.Column('audit_outcome_id', sa.String(length=50), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_outcome_id'], ['audit_outcomes.audit_id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_index(op.f('ix_fraud_labels_label_class'), 'fraud_labels', ['label_class'], unique=False)
    op.create_index(op.f('ix_fraud_labels_work_id'), 'fraud_labels', ['work_id'], unique=False)
    op.create_table('label_reviews',
    sa.Column('review_id', sa.String(length=50), nullable=False),
    sa.Column('label_id', sa.String(length=50), nullable=False),
    sa.Column('reviewer_id', sa.String(length=50), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('agreement', sa.Boolean(), nullable=True),
    sa.Column('disagreement_reason', sa.Text(), nullable=True),
    sa.Column('final_label', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['fraud_labels.label_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_label_reviews_label_id'), 'label_reviews', ['label_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_reviews_label_id'), table_name='label_reviews')
    op.drop_table('label_reviews')
    op.drop_index(op.f('ix_fraud_labels_work_id'), table_name='fraud_labels')
    op.drop_index(op.f('ix_fraud_labels_label_class'), table_name='fraud_labels')
    op.drop_table('fraud_labels')
    op.drop_index(op.f('ix_bidders_tender_id'), table_name='bidders')
    op.drop_table('bidders')
    op.drop_index(op.f('ix_tenders_work_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_tender_package_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_predictions_work_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_run_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_fraud_probability'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_payment_vouchers_work_id'), table_name='payment_vouchers')
    op.drop_index(op.f('ix_payment_vouchers_voucher_date'), table_name='payment_vouchers')
    op.drop_index(op.f('ix_payment_vouchers_contractor_id'), table_name='payment_vouchers')
    op.drop_table('payment_vouchers')
    op.drop_index(op.f('ix_measurement_books_work_id'), table_name='measurement_books')
    op.drop_table('measurement_books')
    op.drop_index(op.f('ix_invoices_work_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inspections_work_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_geotagged_photos_work_id'), table_name='geotagged_photos')
    op.drop_table('geotagged_photos')
    op.drop_index(op.f('ix_complaints_work_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_audit_outcomes_work_id'), table_name='audit_outcomes')
    op.drop_index(op.f('ix_audit_outcomes_fraud_confirmed'), table_name='audit_outcomes')
    op.drop_table('audit_outcomes')
    op.drop_index(op.f('ix_anomalies_work_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_run_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detector_type'), table_name='anomalies')
    op.drop_index('idx_anomalies_composite', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_works_status'), table_name='works')
    op.drop_index(op.f('ix_works_recommended_date'), table_name='works')
    op.drop_index(op.f('ix_works_mp_name'), table_name='works')
    op.drop_index(op.f('ix_works_mp_constituency'), table_name='works')
    op.drop_index(op.f('ix_works_district'), table_name='works')
    op.drop_index(op.f('ix_works_completion_date'), table_name='works')
    op.drop_index(op.f('ix_works_category'), table_name='works')
    op.drop_index('idx_works_mp_date', table_name='works')
    op.drop_index('idx_works_district_date', table_name='works')
    op.drop_table('works')
    op.drop_index('idx_entity_risk_rank', table_name='entity_risks')
    op.drop_table('entity_risks')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pipeline_runs_run_key'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_datasets_file_checksum_sha256'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_contractors_gstin'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_contractor_name'), table_name='contractors')
    op.drop_table('contractors')
    # ### end Alembic commands ###
